FROM java
                                                                                  VOLUME /tmp
                                                                                  ADD microservice-hystrix-dashboard-0.0.1-SNAPSHOT.jar app.jar
                                                                                  RUN bash -c "touch /app.jar"
                                                                                  EXPOSE 8030
                                                                                  ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]